### ISSUE TITLE
Bulk operation initiated by one user suppresses notifications of another user

### ISSUE THREAD

**Issue by mvlasovatl** [atlassian-labs/atlassian-slack-integration-server#13] opened 2020-07-24 13:03 UTC
See more details here: https://jira.atlassian.com/browse/API-245

**Comment by Diana520** [comment] 2021-12-10 15:25
I was trying to reproduce the issue but bug was in Jira 7 that now is not supported. So the issue is closed as obsolete

**Closed by Diana520** 2021-12-10 15:25 UTC
Labels: bug, jira
