### ISSUE TITLE
A single rule does not notify any longer

### ISSUE THREAD

**Issue by alextoind** [atlassian-labs/atlassian-slack-integration-server#24] opened 2020-07-29 10:19 UTC
Hello there,

As reported already in the [Atlassian Community](https://community.atlassian.com/t5/Jira-questions/Jira-Server-for-Slack-notifications-bug/qaq-p/1273380) and in a [Customer Ticket](https://getsupport.atlassian.com/servicedesk/customer/portal/35/CA-893617), there was a bug affecting Jira Server for Slack v2.0.6 that was solved in Jira Server for Slack v2.0.7 and that seems to have come out again in v2.0.11 and v2.0.13.

We are now running Jira Server v8.7 and Jira Server for Slack v2.0.13 and what's happening is that a single rule for a single project is not properly triggered any longer, but all the other rules work fine.

The only difference w.r.t. other rules and we filter for a specific issue type and a specific transition to a custom workflow state, as shown in the following screen: https://www.dropbox.com/sh/zj1za9crjendwfc/AABvpcKauFBliCIvOXQvXzQAa?dl=0&preview=config.png.

If you need something more specific, please let me know.

Best regards,
Alessandro

**Comment by mvlasovatl** [comment] 2020-11-12 17:25
Hey @alextoind !
Could you try to reproduce the issue with newest version of Jira Server for Slack - 2.0.14 [with debug logging enabeld](https://confluence.atlassian.com/slack/using-jira-applications-with-slack-966662163.html#UsingJiraapplicationswithSlack-Debuglogging)? We have added more logging there that might help to find the cause of the issue.

**Comment by alextoind** [comment] 2020-11-13 12:12
Thanks for your time @mvlasovatl!

I attach here a copy-paste from the Jira's log after a simple double transition (the first it is only to enable the second one to trigger).

```
2020-11-13 13:03:56,175+0100 http-nio-8000-exec-16 DEBUG alessandro.tondo 783x28869x1 16xpqnt x.x.x.x:8547,y.y.y.y /slack/issuepanel/data/PROD2020-93 [c.a.j.p.s.storage.json.JsonPropertyStoreStorageStrategy] Getting entity of type 'interface com.atlassian.jira.plugins.slack.model.DedicatedChannel' for issueId=17202 with key=slack.issue.dedicated.channel: None
2020-11-13 13:03:56,504+0100 http-nio-8000-exec-24 DEBUG alessandro.tondo 783x28879x1 16xpqnt x.x.x.x:8483,y.y.y.y /slack/issue-mentions/PROD2020-93/channels [c.a.j.p.s.storage.json.JsonPropertyStoreStorageStrategy] Getting all enities of type 'class com.atlassian.jira.plugins.slack.model.mentions.IssueMention' for issueId=17202: {}
2020-11-13 13:03:56,504+0100 http-nio-8000-exec-24 DEBUG alessandro.tondo 783x28879x1 16xpqnt x.x.x.x:8483,y.y.y.y /slack/issue-mentions/PROD2020-93/channels [c.a.j.p.s.storage.json.JsonPropertyStoreStorageStrategy] No entity of type 'class com.atlassian.jira.plugins.slack.model.mentions.IssueMention' found for issueId=17202
2020-11-13 13:04:01,207+0100 http-nio-8000-exec-12 WARN alessandro.tondo 784x28895x1 16xpqnt x.x.x.x:8512,y.y.y.y /secure/WorkflowUIDispatcher.jspa [r.t.j.plugins.crm.CrmUtilsImpl]  setEmailFromIssue issueId 17202 :: PROD2020-93
2020-11-13 13:04:01,222+0100 http-nio-8000-exec-12 WARN alessandro.tondo 784x28895x1 16xpqnt x.x.x.x:8512,y.y.y.y /secure/WorkflowUIDispatcher.jspa [r.t.j.plugins.crm.CrmUtilsImpl]  setEmailFromIssue issueId 17202 :: PROD2020-93
2020-11-13 13:04:01,222+0100 http-nio-8000-exec-12 WARN alessandro.tondo 784x28895x1 16xpqnt x.x.x.x:8512,y.y.y.y /secure/WorkflowUIDispatcher.jspa [r.t.j.plugins.crm.CrmUtilsImpl]  setEmailFromIssue issueId 17202 :: PROD2020-93
2020-11-13 13:04:01,222+0100 http-nio-8000-exec-12 WARN alessandro.tondo 784x28895x1 16xpqnt x.x.x.x:8512,y.y.y.y /secure/WorkflowUIDispatcher.jspa [r.t.j.plugins.crm.CrmUtilsImpl]  setEmailFromIssue issueId 17202 :: PROD2020-93
2020-11-13 13:04:01,222+0100 http-nio-8000-exec-12 WARN alessandro.tondo 784x28895x1 16xpqnt x.x.x.x:8512,y.y.y.y /secure/WorkflowUIDispatcher.jspa [r.t.j.plugins.crm.CrmUtilsImpl]  setEmailFromIssue issueId 17202 :: PROD2020-93
2020-11-13 13:04:01,222+0100 http-nio-8000-exec-12 WARN alessandro.tondo 784x28895x1 16xpqnt x.x.x.x:8512,y.y.y.y /secure/WorkflowUIDispatcher.jspa [r.t.j.plugins.crm.CrmUtilsImpl]  setEmailFromIssue issueId 17202 :: PROD2020-93
2020-11-13 13:04:01,238+0100 http-nio-8000-exec-12 WARN alessandro.tondo 784x28895x1 16xpqnt x.x.x.x:8512,y.y.y.y /secure/WorkflowUIDispatcher.jspa [r.t.j.plugins.crm.CrmUtilsImpl]  setEmailFromIssue issueId 17202 :: PROD2020-93
2020-11-13 13:04:01,238+0100 http-nio-8000-exec-12 WARN alessandro.tondo 784x28895x1 16xpqnt x.x.x.x:8512,y.y.y.y /secure/WorkflowUIDispatcher.jspa [r.t.j.plugins.crm.CrmUtilsImpl]  setEmailFromIssue issueId 17202 :: PROD2020-93
2020-11-13 13:04:01,254+0100 slack-client:thread-4 DEBUG alessandro.tondo 764x27657x1 1ck1gsa z.z.z.z:52375,y.y.y.y /secure/CommentAssignIssue.jspa [c.a.j.p.s.s.listener.impl.DefaultJiraSlackEventListener] Processing event id=2 for issue key=PROD2020-93, id=17202
2020-11-13 13:04:01,254+0100 slack-client:thread-4 DEBUG alessandro.tondo 764x27657x1 1ck1gsa z.z.z.z:52375,y.y.y.y /secure/CommentAssignIssue.jspa [c.a.j.p.s.storage.json.JsonPropertyStoreStorageStrategy] Getting entity of type 'interface com.atlassian.jira.plugins.slack.model.DedicatedChannel' for issueId=17202 with key=slack.issue.dedicated.channel: None
2020-11-13 13:04:01,254+0100 slack-client:thread-4 DEBUG alessandro.tondo 764x27657x1 1ck1gsa z.z.z.z:52375,y.y.y.y /secure/CommentAssignIssue.jspa [c.a.j.p.s.s.notification.impl.DefaultIssueEventProcessorService] Finding Configurations for event [ISSUE_UPDATED] : 0
2020-11-13 13:04:01,925+0100 automation-rule-executor:thread-1 INFO jirabot     [c.a.jira.index.MonitoringIndexWriter] [lucene-stats] flush stats: snapshotCount=18, totalCount=194, periodSec=1228, flushIntervalMillis=68235, indexDirectory=E:\Atlassian\Application Data\JIRA\caches\indexesV1\issues, indexWriterId=com.atlassian.jira.index.MonitoringIndexWriter@51596327, indexDirectoryId=MMapDirectory@E:\Atlassian\Application Data\JIRA\caches\indexesV1\issues lockFactory=org.apache.lucene.store.NativeFSLockFactory@5f9e977c
2020-11-13 13:04:01,972+0100 http-nio-8000-exec-25 DEBUG alessandro.tondo 784x28903x3 16xpqnt x.x.x.x:8512,y.y.y.y /slack/issuepanel/data/PROD2020-93 [c.a.j.p.s.storage.json.JsonPropertyStoreStorageStrategy] Getting entity of type 'interface com.atlassian.jira.plugins.slack.model.DedicatedChannel' for issueId=17202 with key=slack.issue.dedicated.channel: None
2020-11-13 13:04:02,097+0100 http-nio-8000-exec-21 DEBUG alessandro.tondo 784x28908x1 16xpqnt x.x.x.x:8466,y.y.y.y /slack/issue-mentions/PROD2020-93/channels [c.a.j.p.s.storage.json.JsonPropertyStoreStorageStrategy] Getting all enities of type 'class com.atlassian.jira.plugins.slack.model.mentions.IssueMention' for issueId=17202: {}
2020-11-13 13:04:02,097+0100 http-nio-8000-exec-21 DEBUG alessandro.tondo 784x28908x1 16xpqnt x.x.x.x:8466,y.y.y.y /slack/issue-mentions/PROD2020-93/channels [c.a.j.p.s.storage.json.JsonPropertyStoreStorageStrategy] No entity of type 'class com.atlassian.jira.plugins.slack.model.mentions.IssueMention' found for issueId=17202
2020-11-13 13:04:05,847+0100 http-nio-8000-exec-7 WARN alessandro.tondo 784x28913x1 16xpqnt x.x.x.x:8466,y.y.y.y /secure/WorkflowUIDispatcher.jspa [r.t.j.plugins.crm.CrmUtilsImpl]  setEmailFromIssue issueId 17202 :: PROD2020-93
2020-11-13 13:04:05,863+0100 http-nio-8000-exec-7 WARN alessandro.tondo 784x28913x1 16xpqnt x.x.x.x:8466,y.y.y.y /secure/WorkflowUIDispatcher.jspa [r.t.j.plugins.crm.CrmUtilsImpl]  setEmailFromIssue issueId 17202 :: PROD2020-93
2020-11-13 13:04:05,863+0100 http-nio-8000-exec-7 WARN alessandro.tondo 784x28913x1 16xpqnt x.x.x.x:8466,y.y.y.y /secure/WorkflowUIDispatcher.jspa [r.t.j.plugins.crm.CrmUtilsImpl]  setEmailFromIssue issueId 17202 :: PROD2020-93
2020-11-13 13:04:05,863+0100 http-nio-8000-exec-7 WARN alessandro.tondo 784x28913x1 16xpqnt x.x.x.x:8466,y.y.y.y /secure/WorkflowUIDispatcher.jspa [r.t.j.plugins.crm.CrmUtilsImpl]  setEmailFromIssue issueId 17202 :: PROD2020-93
2020-11-13 13:04:05,863+0100 http-nio-8000-exec-7 WARN alessandro.tondo 784x28913x1 16xpqnt x.x.x.x:8466,y.y.y.y /secure/WorkflowUIDispatcher.jspa [r.t.j.plugins.crm.CrmUtilsImpl]  setEmailFromIssue issueId 17202 :: PROD2020-93
2020-11-13 13:04:05,879+0100 http-nio-8000-exec-7 WARN alessandro.tondo 784x28913x1 16xpqnt x.x.x.x:8466,y.y.y.y /secure/WorkflowUIDispatcher.jspa [r.t.j.plugins.crm.CrmUtilsImpl]  setEmailFromIssue issueId 17202 :: PROD2020-93
2020-11-13 13:04:05,879+0100 http-nio-8000-exec-7 WARN alessandro.tondo 784x28913x1 16xpqnt x.x.x.x:8466,y.y.y.y /secure/WorkflowUIDispatcher.jspa [r.t.j.plugins.crm.CrmUtilsImpl]  setEmailFromIssue issueId 17202 :: PROD2020-93
2020-11-13 13:04:05,879+0100 http-nio-8000-exec-7 WARN alessandro.tondo 784x28913x1 16xpqnt x.x.x.x:8466,y.y.y.y /secure/WorkflowUIDispatcher.jspa [r.t.j.plugins.crm.CrmUtilsImpl]  setEmailFromIssue issueId 17202 :: PROD2020-93
2020-11-13 13:04:05,894+0100 slack-client:thread-5 DEBUG alessandro.tondo 764x27657x1 1ck1gsa z.z.z.z:52375,y.y.y.y /secure/CommentAssignIssue.jspa [c.a.j.p.s.s.listener.impl.DefaultJiraSlackEventListener] Processing event id=2 for issue key=PROD2020-93, id=17202
2020-11-13 13:04:05,894+0100 slack-client:thread-5 DEBUG alessandro.tondo 764x27657x1 1ck1gsa z.z.z.z:52375,y.y.y.y /secure/CommentAssignIssue.jspa [c.a.j.p.s.storage.json.JsonPropertyStoreStorageStrategy] Getting entity of type 'interface com.atlassian.jira.plugins.slack.model.DedicatedChannel' for issueId=17202 with key=slack.issue.dedicated.channel: None
2020-11-13 13:04:05,894+0100 slack-client:thread-5 DEBUG alessandro.tondo 764x27657x1 1ck1gsa z.z.z.z:52375,y.y.y.y /secure/CommentAssignIssue.jspa [c.a.j.p.s.s.notification.impl.DefaultIssueEventProcessorService] Finding Configurations for event [ISSUE_UPDATED] : 0
2020-11-13 13:04:06,457+0100 http-nio-8000-exec-12 DEBUG alessandro.tondo 784x28920x2 16xpqnt x.x.x.x:8466,y.y.y.y /slack/issuepanel/data/PROD2020-93 [c.a.j.p.s.storage.json.JsonPropertyStoreStorageStrategy] Getting entity of type 'interface com.atlassian.jira.plugins.slack.model.DedicatedChannel' for issueId=17202 with key=slack.issue.dedicated.channel: None
2020-11-13 13:04:06,566+0100 http-nio-8000-exec-2 DEBUG alessandro.tondo 784x28924x1 16xpqnt x.x.x.x:8470,y.y.y.y /slack/issue-mentions/PROD2020-93/channels [c.a.j.p.s.storage.json.JsonPropertyStoreStorageStrategy] Getting all enities of type 'class com.atlassian.jira.plugins.slack.model.mentions.IssueMention' for issueId=17202: {}
2020-11-13 13:04:06,566+0100 http-nio-8000-exec-2 DEBUG alessandro.tondo 784x28924x1 16xpqnt x.x.x.x:8470,y.y.y.y /slack/issue-mentions/PROD2020-93/channels [c.a.j.p.s.storage.json.JsonPropertyStoreStorageStrategy] No entity of type 'class com.atlassian.jira.plugins.slack.model.mentions.IssueMention' found for issueId=17202
2020-11-13 13:04:16,488+0100 JiraIndexCommitThread-13 INFO      [c.a.jira.index.MonitoringIndexWriter] [lucene-stats] flush stats: snapshotCount=1, totalCount=66, periodSec=1170, flushIntervalMillis=1170003, indexDirectory=E:\Atlassian\Application Data\JIRA\caches\indexesV1\comments, indexWriterId=com.atlassian.jira.index.MonitoringIndexWriter@671743ca, indexDirectoryId=MMapDirectory@E:\Atlassian\Application Data\JIRA\caches\indexesV1\comments lockFactory=org.apache.lucene.store.NativeFSLockFactory@5f9e977c
2020-11-13 13:04:16,488+0100 JiraIndexCommitThread-2 INFO      [c.a.jira.index.MonitoringIndexWriter] [lucene-stats] flush stats: snapshotCount=8, totalCount=78, periodSec=1229, flushIntervalMillis=153749, indexDirectory=E:\Atlassian\Application Data\JIRA\caches\indexesV1\changes, indexWriterId=com.atlassian.jira.index.MonitoringIndexWriter@1a2ba05b, indexDirectoryId=MMapDirectory@E:\Atlassian\Application Data\JIRA\caches\indexesV1\changes lockFactory=org.apache.lucene.store.NativeFSLockFactory@5f9e977c
2020-11-13 13:04:16,488+0100 JiraIndexCommitThread-5 INFO      [c.a.jira.index.MonitoringIndexWriter] [lucene-stats] flush stats: snapshotCount=2, totalCount=56, periodSec=1170, flushIntervalMillis=585001, indexDirectory=E:\Atlassian\Application Data\JIRA\caches\indexesV1\worklogs, indexWriterId=com.atlassian.jira.index.MonitoringIndexWriter@186049f3, indexDirectoryId=MMapDirectory@E:\Atlassian\Application Data\JIRA\caches\indexesV1\worklogs lockFactory=org.apache.lucene.store.NativeFSLockFactory@5f9e977c
```

Please let me know if you need additional information

**Comment by mvlasovatl** [comment] 2021-03-10 15:40
The log doesn't point to any obvious issue, but this issue was reported by other customers as well, and I managed to reproduce it. It feels like it is a race condition issue. Currently the plugin relies on `IssueEvent` event, but it seems to be triggered before or after the changelog is saved to the Jira database, so the app is unable to detect changed fields sometimes. The solution here is to migrate to another event - `IssueChangedEvent`. It provides a way to retrieve a consistent changelog.

**Comment by mvlasovatl** [comment] 2021-03-19 14:18
The issue was fixed in recently release Jira Server for Slack 2.0.16.

**Closed by mvlasovatl** 2021-03-19 14:18 UTC
Labels: bug, jira

**Comment by mvlasovatl** [comment] 2021-03-22 13:59
This issue in JAC: https://jira.atlassian.com/browse/API-396
