### ISSUE TITLE
When a user adds a comment in a page, the resulting Slack notification does not correctly refer to the comment creator. 

### ISSUE THREAD

**Issue by tknopp1** [atlassian-labs/atlassian-slack-integration-server#122] opened 2021-07-14 13:55 UTC
Issue Summary
When a user adds a comment in a Confluence page, the resulting notification in Slack refer as though the creator of the page has made a comment instead of the actual user who made the comment.

Version
The issue was tested in version 2.0.2

Steps to Reproduce
Login to Confluence, lets say this user has the username user1.
Create or take not of an existing Space.
Create a page in the above space.
Connect Confluence with Slack.
Setup Confluence to receive notification from a the above space.
Click on the User Avatar > Settings > Slack Notification
Ensure to set When pages and posts I created get new comments to true.
Ensure that you have connected your user with a Slack account via Slack Accounts option.
With the above set, you should get notifications when another user comments on a page you have created.
Log out.
Login using a different user (lets call them user2), and add a comment to the page that was created by user1.
Expected Results
In Slack the notificat should read.

 user2 commented on page_name in SpaceName
 > Lorem Ipsum
Actual Results
In Slack the notification reads:

 user1 commented on page_name in SpaceName
 > Lorem Ipsum
Note
The issue occurs in Pages as well as in blogs.

Workaround
No known workaround

Copied from -> https://jira.atlassian.com/browse/API-213

**Comment by mvlasovatl** [comment] 2021-07-15 10:32
I believe it's a better described duplicate of #10.

**Comment by mvlasovatl** [comment] 2022-03-10 15:06
This issue was tackled in #168 that was merged to `dev`. It is pending next release now.

**Comment by mvlasovatl** [comment] 2022-03-18 18:01
The fix was included into Confluence Server for Slack 2.1.4.

**Closed by mvlasovatl** 2022-03-18 18:01 UTC
Labels: bug, confluence
