### ISSUE TITLE
Duplicated message for the Issue created event

### ISSUE THREAD

**Issue by gonchik** [atlassian-labs/atlassian-slack-integration-server#199] opened 2022-05-23 08:45 UTC
Hi! 

We met with next situation on the latest release of app. 
1. Once fired issue created event
2. Slack notifier for issue creation event notifying twice instead of once. 

Cheers,
Gonchik

**Comment by gonchik** [comment] 2022-05-25 08:14
Hi! 
I made a rollback a few releases back, no luck. 
Looks like the problem Jira core module.

**Comment by mvlasovatl** [comment] 2022-06-14 14:50
Hey @gonchik ! I have just tried to reproduce the issue with latest Jira Server for Slack plugin version (3.0.1) on Jira Software 8.20.4 and failed. Only one notification is delivered on issue creation for me. I feel like that the issue is in your Jira or plugin configuration. Would you like to share more details about your environment and steps for reproducing the issue?

**Comment by mvlasovatl** [comment] 2023-01-19 14:39
Closing as an obsolete.

**Closed by mvlasovatl** 2023-01-19 14:39 UTC
Labels: bug, jira

**Comment by gonchik** [comment] 2023-01-19 22:56
Hi @mvlasovatl , 
sorry, I forgot to follow up. 
it has been fixed by removing all configs related to the Slack app on DB level  in Jira. 
The cause was duplicated rules. Where one of then was not visible

**Comment by mvlasovatl** [comment] 2023-01-20 13:20
Interesting. It was supposed to be fixed in #145, that was released in Jira Server for Slack 2.0.23. Duplicates that already existed in the database should have been fixed on new plugin version installation. Is older version of the app used on your Jira instance? If not, then it may be a sign of incomplete fix. If you are able to reproduce the issue, please share the steps.
