### ISSUE TITLE
Regression in Jira plugin 2.0.14: infinite DMs loop

### ISSUE THREAD

**Issue by procule** [atlassian-labs/atlassian-slack-integration-server#67] opened 2020-11-16 17:53 UTC
Hi,
It looks like that commit https://github.com/atlassian-labs/atlassian-slack-integration-server/commit/1a326b79c2682b9514aa481e7e0a2119f4ef5eae or something related created a very disruptive regression.

We had to reconnect the Jira Slack integration to our workspace after modifying some scope permissions. It invalidated all users OAuth token. 

Now, when someone triggers a "ticket mentioned event" in a channel, he gets spam by the plugin with infinite Slack DM as seen here:
![https://i.imgur.com/VtLO0i6.png](https://i.imgur.com/VtLO0i6.png)

We have to disable and re-enable the Jira plugin for the notifications to stop.

If the user reconnects the Jira Slack integration in his profile, it solves the issue.

**Comment by mvlasovatl** [comment] 2020-11-17 14:33
Hello Olivier! Thanks for the report.
I failed to reproduce the issue though. Could you describe steps in more details?
1. How have you invalidated all user tokens and was able to open a direct conversation with Jira Server bot after that?
2. What means "someone triggers a ticket mentioned event"? The plugin doesn't have such event among supported ones.

**Comment by procule** [comment] 2020-11-27 18:19
Hi @mvlasovatl , Sorry for the delay. I have more informations to share:

1. There was a change in the Slack OAuth permissions and the Slack Application invalidated the Bot OAuth Access Token. We got that screen: 
![https://i.imgur.com/IemFhAs.png](https://i.imgur.com/IemFhAs.png)

I went to update the credentials by adding the new Bot OAuth Access Token and reconnected the Plugin. I don't have a screenshot but I remember that there was a message saying that it would invalidate all users' OAuth Tokens.

2. Of course it has: [jira-slack-server-integration/jira-slack-server-integration-plugin/src/main/java/com/atlassian/jira/plugins/slack/service/listener/SlackEventHandlerService.java](https://github.com/atlassian-labs/atlassian-slack-integration-server/blob/master/jira-slack-server-integration/jira-slack-server-integration-plugin/src/main/java/com/atlassian/jira/plugins/slack/service/listener/SlackEventHandlerService.java)

I downgraded to earlier version 2.0.13, but the bug is still there so it was not a regression in 2.0.14 as I thought.

Here is an example (by DMing directly the Bot, the same thing happens when the ticket is mentioned in a channel where the Bot is. The loop always come from DM from the Bot whether the mention was in DM or in a channel)
![https://i.imgur.com/rliQ66M.png](https://i.imgur.com/rliQ66M.png)

This created this in the Jira instance log file:

> 2020-11-27 12:37:24,122-0500 MainThread WARN anonymous 757x2199008x1 - 0.0.0.148 /slack/event [c.a.p.slack.util.ResponseMapper] Error when performing request to Slack: conversations.info/DGALSR57D
com.google.gson.JsonParseException: Unsupported layout block type: rich_text
	at com.github.seratch.jslack.common.json.GsonLayoutBlockFactory.getLayoutClassInstance(GsonLayoutBlockFactory.java:36)
	at com.github.seratch.jslack.common.json.GsonLayoutBlockFactory.deserialize(GsonLayoutBlockFactory.java:19)
	at com.github.seratch.jslack.common.json.GsonLayoutBlockFactory.deserialize(GsonLayoutBlockFactory.java:12)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
	at com.google.gson.Gson.fromJson(Gson.java:927)
	at com.google.gson.Gson.fromJson(Gson.java:892)
	at com.google.gson.Gson.fromJson(Gson.java:841)
	at com.google.gson.Gson.fromJson(Gson.java:813)
	at com.github.seratch.jslack.common.http.SlackHttpClient.parseJsonResponse(SlackHttpClient.java:81)
	at com.github.seratch.jslack.api.methods.impl.MethodsClientImpl.doPostFormWithToken(MethodsClientImpl.java:913)
	at com.github.seratch.jslack.api.methods.impl.MethodsClientImpl.conversationsInfo(MethodsClientImpl.java:354)
	at com.atlassian.plugins.slack.api.client.DefaultSlackClient.lambda$getConversationsInfoCached$15(DefaultSlackClient.java:356)
	at com.atlassian.plugins.slack.api.client.cache.SlackResponseCache.lambda$getAndCacheIfSuccessful$0(SlackResponseCache.java:55)
	at com.atlassian.cache.ehcache.ReferenceCacheLoader.load(ReferenceCacheLoader.java:31)
	at com.atlassian.cache.ehcache.wrapper.ValueProcessorEhcacheLoaderDecorator.load(ValueProcessorEhcacheLoaderDecorator.java:30)
	at net.sf.ehcache.Cache.loadValueUsingLoader(Cache.java:3373)
	at net.sf.ehcache.Cache.getWithLoader(Cache.java:1859)
	at com.atlassian.cache.ehcache.DelegatingCache.get(DelegatingCache.java:128)
	at com.atlassian.jira.cache.DeferredReplicationCache.get(DeferredReplicationCache.java:54)
	at com.atlassian.plugins.slack.api.client.cache.SlackResponseCache.getAndCacheIfSuccessful(SlackResponseCache.java:52)
	at com.atlassian.plugins.slack.api.client.DefaultSlackClient.getConversationsInfoCached(DefaultSlackClient.java:352)
	at com.atlassian.plugins.slack.api.client.DefaultSlackClient.lambda$getConversationsInfo$16(DefaultSlackClient.java:370)
	at com.atlassian.plugins.slack.util.ResponseMapper.toEither(ResponseMapper.java:23)
	at com.atlassian.plugins.slack.api.client.DefaultSlackClient.getConversationsInfo(DefaultSlackClient.java:368)
	at com.atlassian.jira.plugins.slack.mentions.storage.cache.MentionChannelCacheLoader.lambda$fetchCacheLoad$3(MentionChannelCacheLoader.java:36)
	at io.atlassian.fugue.Either$Right.fold(Either.java:641)
	at com.atlassian.jira.plugins.slack.mentions.storage.cache.MentionChannelCacheLoader.fetchCacheLoad(MentionChannelCacheLoader.java:34)
	at com.atlassian.jira.plugins.slack.mentions.storage.cache.MentionChannelCacheLoader.fetchCacheLoad(MentionChannelCacheLoader.java:13)
	at com.atlassian.jira.plugins.slack.mentions.storage.cache.SlackApiCacheLoader.load(SlackApiCacheLoader.java:26)
	at com.atlassian.jira.plugins.slack.mentions.storage.cache.SlackApiCacheLoader.load(SlackApiCacheLoader.java:15)
	at com.atlassian.cache.ehcache.wrapper.ValueProcessorAtlassianCacheLoaderDecorator.load(ValueProcessorAtlassianCacheLoaderDecorator.java:26)
	at com.atlassian.cache.ehcache.LoadingCache.getFromLoader(LoadingCache.java:134)
	at com.atlassian.cache.ehcache.SynchronizedLoadingCacheDecorator.synchronizedLoad(SynchronizedLoadingCacheDecorator.java:29)
	at com.atlassian.cache.ehcache.LoadingCache.loadValueAndReleaseLock(LoadingCache.java:102)
	at com.atlassian.cache.ehcache.LoadingCache.get(LoadingCache.java:81)
	at com.atlassian.cache.ehcache.DelegatingCache.get(DelegatingCache.java:108)
	at com.atlassian.jira.cache.DeferredReplicationCache.get(DeferredReplicationCache.java:48)
	at com.atlassian.jira.plugins.slack.storage.cache.AbstractCacheableEntityManager.get(AbstractCacheableEntityManager.java:60)
	at com.atlassian.jira.plugins.slack.service.listener.SlackEventHandlerService.handleMessage(SlackEventHandlerService.java:152)
	at com.atlassian.jira.plugins.slack.service.listener.SlackEventListener.messageReceived(SlackEventListener.java:156)
	... 3 filtered
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.atlassian.event.internal.SingleParameterMethodListenerInvoker.invoke(SingleParameterMethodListenerInvoker.java:42)
	at com.atlassian.event.internal.AsynchronousAbleEventDispatcher.lambda$null$0(AsynchronousAbleEventDispatcher.java:37)
	at com.atlassian.event.internal.AsynchronousAbleEventDispatcher.dispatch(AsynchronousAbleEventDispatcher.java:85)
	at com.atlassian.event.internal.LockFreeEventPublisher$Publisher.dispatch(LockFreeEventPublisher.java:220)
	at com.atlassian.event.internal.LockFreeEventPublisher.publish(LockFreeEventPublisher.java:96)
	... 2 filtered
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.atlassian.plugin.util.ContextClassLoaderSettingInvocationHandler.invoke(ContextClassLoaderSettingInvocationHandler.java:26)
	at com.sun.proxy.$Proxy113.publish(Unknown Source)
	... 2 filtered
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
	at org.eclipse.gemini.blueprint.service.importer.support.internal.aop.ServiceInvoker.doInvoke(ServiceInvoker.java:56)
	at org.eclipse.gemini.blueprint.service.importer.support.internal.aop.ServiceInvoker.invoke(ServiceInvoker.java:60)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.springframework.aop.support.DelegatingIntroductionInterceptor.doProceed(DelegatingIntroductionInterceptor.java:136)
	at org.springframework.aop.support.DelegatingIntroductionInterceptor.invoke(DelegatingIntroductionInterceptor.java:124)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.eclipse.gemini.blueprint.service.util.internal.aop.ServiceTCCLInterceptor.invokeUnprivileged(ServiceTCCLInterceptor.java:70)
	at org.eclipse.gemini.blueprint.service.util.internal.aop.ServiceTCCLInterceptor.invoke(ServiceTCCLInterceptor.java:53)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.eclipse.gemini.blueprint.service.importer.support.LocalBundleContextAdvice.invoke(LocalBundleContextAdvice.java:57)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.springframework.aop.support.DelegatingIntroductionInterceptor.doProceed(DelegatingIntroductionInterceptor.java:136)
	at org.springframework.aop.support.DelegatingIntroductionInterceptor.invoke(DelegatingIntroductionInterceptor.java:124)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
	at com.sun.proxy.$Proxy6045.publish(Unknown Source)
	at com.atlassian.plugins.slack.rest.SlackWebHookResource.webEvent(SlackWebHookResource.java:153)
	... 3 filtered
	at java.lang.reflect.Method.invoke(Method.java:498)
	... 19 filtered
	at com.atlassian.plugins.rest.module.RestDelegatingServletFilter$JerseyOsgiServletContainer.doFilter(RestDelegatingServletFilter.java:160)
	... 1 filtered
	at com.atlassian.plugins.rest.module.RestDelegatingServletFilter.doFilter(RestDelegatingServletFilter.java:70)
	... 32 filtered
	at com.atlassian.servicedesk.internal.web.ExternalCustomerLockoutFilter.doFilter(ExternalCustomerLockoutFilter.java:55)
	... 4 filtered
	at com.atlassian.diagnostics.internal.platform.monitor.http.HttpRequestMonitoringFilter.doFilter(HttpRequestMonitoringFilter.java:55)
	... 3 filtered
	at com.atlassian.web.servlet.plugin.request.RedirectInterceptingFilter.doFilter(RedirectInterceptingFilter.java:21)
	... 33 filtered
	at com.atlassian.ratelimiting.internal.filter.RateLimitFilter.doFilter(RateLimitFilter.java:73)
	... 10 filtered
	at com.atlassian.jira.security.JiraSecurityFilter.lambda$doFilter$0(JiraSecurityFilter.java:66)
	... 1 filtered
	at com.atlassian.jira.security.JiraSecurityFilter.doFilter(JiraSecurityFilter.java:64)
	... 20 filtered
	at com.atlassian.jira.servermetrics.CorrelationIdPopulatorFilter.doFilter(CorrelationIdPopulatorFilter.java:30)
	... 5 filtered
	at com.atlassian.servicedesk.internal.web.CustomerContextSettingFilter.doFilter(CustomerContextSettingFilter.java:118)
	... 4 filtered
	at com.atlassian.ratelimiting.internal.filter.RateLimitPreAuthFilter.doFilter(RateLimitPreAuthFilter.java:71)
	... 10 filtered
	at com.atlassian.jira.servermetrics.MetricsCollectorFilter.doFilter(MetricsCollectorFilter.java:25)
	... 45 filtered
	at net.youngaweb.jira.ServletFilterKa.doFilter(ServletFilterKa.kt:302)
	... 3 filtered
	at com.atlassian.plugins.slack.analytics.SlackAnalyticsFilter.doFilter(SlackAnalyticsFilter.java:35)
	... 14 filtered
	at com.atlassian.jira.security.JiraSecurityFilter.lambda$doFilter$0(JiraSecurityFilter.java:66)
	... 1 filtered
	at com.atlassian.jira.security.JiraSecurityFilter.doFilter(JiraSecurityFilter.java:64)
	... 32 filtered
	at com.atlassian.jira.servermetrics.CorrelationIdPopulatorFilter.doFilter(CorrelationIdPopulatorFilter.java:30)
	... 5 filtered
	at com.atlassian.servicedesk.internal.web.CustomerContextSettingFilter.lambda$invokeFilterChain$0(CustomerContextSettingFilter.java:215)
	at com.atlassian.servicedesk.internal.api.util.context.ReentrantThreadLocalBasedCodeContext.rteInvoke(ReentrantThreadLocalBasedCodeContext.java:136)
	at com.atlassian.servicedesk.internal.api.util.context.ReentrantThreadLocalBasedCodeContext.runOutOfContext(ReentrantThreadLocalBasedCodeContext.java:89)
	at com.atlassian.servicedesk.internal.utils.context.CustomerContextServiceImpl.runOutOfCustomerContext(CustomerContextServiceImpl.java:47)
	at com.atlassian.servicedesk.internal.web.CustomerContextSettingFilter.outOfCustomerContext(CustomerContextSettingFilter.java:206)
	at com.atlassian.servicedesk.internal.web.CustomerContextSettingFilter.doFilterImpl(CustomerContextSettingFilter.java:134)
	at com.atlassian.servicedesk.internal.web.CustomerContextSettingFilter.doFilter(CustomerContextSettingFilter.java:123)
	... 9 filtered
	at com.atlassian.jwt.internal.servlet.JwtAuthFilter.doFilter(JwtAuthFilter.java:37)
	... 3 filtered
	at com.atlassian.web.servlet.plugin.request.RedirectInterceptingFilter.doFilter(RedirectInterceptingFilter.java:21)
	... 4 filtered
	at com.atlassian.web.servlet.plugin.LocationCleanerFilter.doFilter(LocationCleanerFilter.java:36)
	... 7 filtered
	at com.atlassian.plugins.slack.rest.RequestCachingServletFilter.doFilter(RequestCachingServletFilter.java:40)
	... 25 filtered
	at com.atlassian.jira.servermetrics.MetricsCollectorFilter.doFilter(MetricsCollectorFilter.java:25)
	... 25 filtered
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
2020-11-27 12:37:24,148-0500 jira-slack-plugin:thread-2 INFO anonymous 757x2199008x1 - 0.0.0.148 /slack/event [c.a.j.p.s.s.task.impl.SendNotificationTask] Found 1 messages to send to Slack
2020-11-27 12:37:24,149-0500 jira-slack-plugin:thread-3 INFO anonymous 757x2199008x1 - 0.0.0.148 /slack/event [c.a.j.p.s.s.task.impl.SendNotificationTask] Sending notification to Slack channel DGALSR57D
2020-11-27 12:37:25,407-0500 jira-slack-plugin:thread-4 INFO anonymous 757x2199010x1 - 0.0.0.218 /slack/event [c.a.j.p.s.s.task.impl.SendNotificationTask] Found 1 messages to send to Slack
2020-11-27 12:37:25,407-0500 jira-slack-plugin:thread-5 INFO anonymous 757x2199010x1 - 0.0.0.218 /slack/event [c.a.j.p.s.s.task.impl.SendNotificationTask] Sending notification to Slack channel DGALSR57D
2020-11-27 12:37:26,118-0500 jira-slack-plugin:thread-1 INFO anonymous 757x2199008x1 - 0.0.0.148 /slack/event [c.a.j.p.s.s.task.impl.SendNotificationTask] Found 1 messages to send to Slack
2020-11-27 12:37:26,118-0500 jira-slack-plugin:thread-2 INFO anonymous 757x2199008x1 - 0.0.0.148 /slack/event [c.a.j.p.s.s.task.impl.SendNotificationTask] Sending notification to Slack channel DGALSR57D
2020-11-27 12:37:27,394-0500 jira-slack-plugin:thread-3 INFO anonymous 757x2199008x1 - 0.0.0.148 /slack/event [c.a.j.p.s.s.task.impl.SendNotificationTask] Found 1 messages to send to Slack

**DGALSR57D** is the Slack ID of the **Jira Server** Bot

**Comment by Diana520** [comment] 2021-12-07 14:50
I tried to reproduce the issue but i failed to do that. Do you still experience the issue? If yes, please provide me detailed steps how to reproduce it. If no, it could happen that during this time we have solved this issue in plugin accidentally or the reason of issue was fixed in Slack.

**Comment by mvlasovatl** [comment] 2022-03-18 17:57
We weren't able to reproduce the issue, so I close it.

**Closed by mvlasovatl** 2022-03-18 17:57 UTC
Labels: bug, jira
